version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: 'pkt_db'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    command: mongod --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'pkt123'
volumes:
  mongodata:
    driver: local
